name: Check Pull Request
on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                job:
                    - affected:version-check
                    - format:check
                    - affected:lint
                    - affected:test
                    - affected:build
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npx nx ${{ matrix.job }} --base=origin/main
