name: Release
on:
  push:
    branches:
      - 'github-actions'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - format:check
          - affected:lint
          - affected:test
          - affected:build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npx nx ${{ matrix.job }}
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npx nx affected --base=origin/main --target=publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
