name: Release Libraries
on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                job:
                    - format:check
                    - affected:lint
                    - affected:test
                    - affected:build
        steps:
            - uses: nrwl/last-successful-commit-action@v1
              id: last_successful_commit
              with:
                  branch: 'main'
                  workflow_id: 'main.yml'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npx nx ${{ matrix.job }} --base=${{ steps.last_successful_commit.outputs.commit_hash }}
    publish:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: nrwl/last-successful-commit-action@v1
              id: last_successful_commit
              with:
                  branch: 'main'
                  workflow_id: 'main.yml'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npx nx affected --target=publish --base=${{ steps.last_successful_commit.outputs.commit_hash }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
