name: Test
on:
    pull_request:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions-ecosystem/action-push-tag@v1
              with:
                  tag: test
